device: 'cuda'
resume: '../tools/vector_run/glhwater/vlras/train/180_50_32/best_model.pth'
corner_angle_threshold: 180
noncorner_angle_threshold: 180
seed: 2333
model: 'vlras'
learn_rate: 0.001
lr_patience: 10
down_ratio: 4

dataset: 'glhwater'

image_path: "/home/data/vector_data/GLH_water_dataset/raw/test/img/"
result_json: "/home/data/vector_data/GLH_water_dataset/raw/test/predict/coco_result/swinl_upernet_vlras_180_d50_32.json"
coco_predictions: "/home/data/vector_data/GLH_water_dataset/raw/test/predict/coco_result/swin_l.json"
coco_labels: "/home/data/vector_data/GLH_water_dataset/raw/test/coco_label_with_hole.json"

visual: False

num_points: 32
corner_threshold: 0.1
d: 50

backbone_path: "../tools/seg_run/glhwater/1_5_10/swin_l/best_model.pth"

num_workers: 4
batch_size: 32
epochs: 200

run_dir: 'vector_run'
