device: 'cuda'
resume: null

seed: 2333
model: 'vlras'
loss_type: 'angle'

corner_angle_threshold: 135
noncorner_angle_threshold: 135

learn_rate: 0.001
lr_patience: 5
down_ratio: 4
weight_regression: 1.0
weight_classification: 1.0
weight_angle: 1.0

dataset: 'vhrroad'

train_h5_path: "../data/datasets/VHR_road_dataset/h5_file/whu_building_vector_train.h5"
image_path: "../data/datasets/VHR_road_dataset/"

num_points: 32
corner_threshold: 0.1
d: 25

backbone_path: './seg_run/vhrroad/1_5_10/swin_l/best_model.pth'

num_workers: 4
batch_size: 32
epochs: 30
eval_whole: True

run_dir: 'vector_run'